{% set name = "auxiliary" %}
{% set version = "0.4.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/auxiliary-{{ version }}.tar.gz
  sha256: 425e07dedd48ad00a0532fd10911e4dde02b56b603cb6f6dc4a7488afa482c57

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >={{ python_min }}
    - nibabel >=3.0
    - numpy >=1.24
    - tifffile >=2023.8.25
    - path >=17.0.0
    - pillow >=10.0.0
    - simpleitk >=2.2.1
    - loguru >=0.7.3
    - dcm2niix >=1.0.20250506

test:
  imports:
    - auxiliary.nifti.io
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/BrainLesion/auxiliary
  summary: I/O handling for medical images.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
